[package]
name = "evilbocchi/ejt"
version = "2.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "A library for interacting with difficulties in the EToH Joke Towers wiki."
include = ["out", "out/**", "default.project.json", "LICENSE", "wally.toml"]
exclude = ["*"]

[dependencies]